set (CMAKE_SYSTEM_PROCESSOR "$ENV{PLATFORM_NAME}" CACHE STRING "")
set (CROSS_PREFIX           "$ENV{TOOLCHAIN_NAME}-" CACHE STRING "")

# libsysfs
set (LIBSYSFS_LIBRARY       "$ENV{LIBSYSFS_PATH}/build/lib/libsysfs.so" CACHE STRING "")
set (LIBSYSFS_INCLUDE_DIR   "$ENV{LIBSYSFS_PATH}/build/include/" CACHE STRING "")
set (CMAKE_C_FLAGS          "-I$ENV{LIBSYSFS_PATH}/build/include/" CACHE STRING "")

# libhugetlbfs
set (HUGETLBFS_INCLUDE_DIR  "$ENV{LIBHUGETLBFS_PATH}/" CACHE STRING "")
set (HUGETLBFS_LIBRARY      "$ENV{LIBHUGETLBFS_PATH}/obj64/libhugetlbfs.so" CACHE STRING "")

# libmetal
set (LIBMETAL_LIB           "$ENV{LIBMETAL_PATH}/build/usr/local/lib/libmetal.so" CACHE STRING "")
set (LIBMETAL_INCLUDE_DIR   "$ENV{LIBMETAL_PATH}/build/usr/local/include/" CACHE STRING "")

set(WITH_TESTS OFF)

set (CMAKE_SYSTEM_NAME  "$ENV{SYSTERM_NAME}" CACHE STRING "")
set (CMAKE_C_COMPILER   "${CROSS_PREFIX}gcc" CACHE STRING "")
set (CMAKE_CXX_COMPILER "${CROSS_PREFIX}g++" CACHE STRING "")
set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER CACHE STRING "")
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER CACHE STRING "")
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER CACHE STRING "")
