set (CMAKE_SYSTEM_PROCESSOR "$ENV{PLATFORM_NAME}" CACHE STRING "")
set (CROSS_PREFIX           "$ENV{TOOLCHAIN_NAME}-" CACHE STRING "")
get_filename_component(CURRENT_DIR ${CMAKE_CURRENT_SOURCE_DIR} DIRECTORY)
# libsysfs
set (LIBSYSFS_LIB_DIR       "$ENV{LIBSYSFS_PATH}/build/lib/" CACHE STRING "")
set (LIBSYSFS_INCLUDE_DIR   "$ENV{LIBSYSFS_PATH}/build/include/" CACHE STRING "")

# libhugetlbfs
set (HUGETLBFS_INCLUDE_DIR  "$ENV{LIBHUGETLBFS_PATH}/" CACHE STRING "")
set (HUGETLBFS_LIB_DIR      "$ENV{LIBHUGETLBFS_PATH}/obj64/" CACHE STRING "")

# libmetal
set (LIBMETAL_LIB_DIR       "$ENV{LIBMETAL_PATH}/build/usr/local/lib/" CACHE STRING "")
set (LIBMETAL_INCLUDE_DIR   "$ENV{LIBMETAL_PATH}/build/usr/local/include/" CACHE STRING "")

# libopen-amp
set (LIBOPENAMP_LIB_DIR     "$ENV{LIBOPENAMP_PATH}/build/usr/local/lib/" CACHE STRING "")
set (LIBOPENAMP_INCLUDE_DIR "$ENV{LIBOPENAMP_PATH}/build/usr/local/include/" CACHE STRING "")

# platform docking
set (LIBDOCKING_LIB_DIR     "$ENV{LIBDOCKING_PATH}/build/" CACHE STRING "")
set (LIBDOCKING_INCLUDE_DIR "$ENV{LIBDOCKING_PATH}" CACHE STRING "")

set(WITH_TESTS OFF)

set (CMAKE_SYSTEM_NAME  "$ENV{SYSTERM_NAME}" CACHE STRING "")
set (CMAKE_C_COMPILER   "${CROSS_PREFIX}gcc" CACHE STRING "")
set (CMAKE_CXX_COMPILER "${CROSS_PREFIX}g++" CACHE STRING "")
